stages:
  preprocess:                # name of the stage
    # wdir: (repo root)
    cmd: python -u scripts/pipeline/B1_Run_Compiler.py
    deps:
      # files
      - scripts/pipeline/B1_Compiler.py
      - inputs/config/Config_MOMF_T1_A.yaml

      # folder with data
      - inputs/A1_Outputs/
      - inputs/A2_Extra_Inputs/
    outs:
      # files
      - outputs/A2_Structure_Lists.xlsx

      # folder with data
      - outputs/A2_Output_Params/

  executing:                     # name of the stage
    # wdir: (repo root)
    cmd: python -u scripts/pipeline/B2_Executing_OG_Model.py
    deps:
      # files
      - inputs/config/Config_MOMF_T1_AB.yaml
      - inputs/model/osemosys_fast_preprocessed.txt
      - scripts/tools/concatenate_relac.py
      - scripts/pipeline/Z_AUX_capital_annualization_script.py

      # folder with data
      - outputs/A2_Output_Params/
      - inputs/Miscellaneous/

    outs:
      # folder with data (without cache)
      - outputs/A2_Outputs_Params_otoole/:
          cache: false
          persist: true
      - outputs/Executables/:
          cache: false
          persist: true

      # files (without cache)
      - outputs/RELAC_TX_Inputs.csv:
          cache: false
          persist: true
      - outputs/RELAC_TX_Inputs_fecha.csv:
          cache: false
          persist: true
      - outputs/RELAC_TX_Outputs.csv:
          cache: false
          persist: true
      - outputs/RELAC_TX_Outputs_fecha.csv:
          cache: false
          persist: true
      - outputs/RELAC_TX_Combined_Inputs_Outputs.csv:
          cache: false
          persist: true
      - outputs/RELAC_TX_Combined_Inputs_Outputs_fecha.csv:
          cache: false
          persist: true